# Define build
[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

# Project details
[project]
name = "flask_ci"
version = "0.0.1"
description = "Practice CICD using a basic flask app to docker container"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "flask>=3.1.3",
    "gunicorn>=26.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.setuptools.packages.find]
where = ['src']
